# Generated by Django 4.1.6 on 2023-02-20 14:30

from django.db import migrations

def create_plans(apps, schema_editor):
    Plan = apps.get_model('ImageUploader', 'Plan')
    Plan.objects.create(name='Basic', thumbnail_200=True, thumbnail_400=False, original_file=False, expiring_links=False)
    Plan.objects.create(name='Premium', thumbnail_200=True, thumbnail_400=True, original_file=True, expiring_links=False)
    Plan.objects.create(name='Enterprise', thumbnail_200=True, thumbnail_400=True, original_file=True, expiring_links=True)

class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_plans),
    ]