# Generated by Django 4.1.6 on 2023-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
