# Generated by Django 4.1.6 on 2023-02-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0002_image_thumbnail_delete_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='large_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='large_thumbnail'),
        ),
        migrations.AddField(
            model_name='image',
            name='small_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='small_thumbnail'),
        ),
    ]
