# Generated by Django 4.1.6 on 2023-02-20 14:54


import ImageUploader.models
from django.db import migrations, models
import django.db.models.deletion


def set_default_account_tier(apps, schema_editor):
    CustomUser = apps.get_model('ImageUploader', 'CustomUser')
    Plan = apps.get_model('ImageUploader', 'Plan')
    basic_plan = Plan.objects.get(name='Basic')
    CustomUser.objects.filter(account_tier=None).update(account_tier=basic_plan)

class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0002_auto_20230220_1554'),
    ]

    operations = [
        migrations.RunPython(set_default_account_tier),
    ]