# Generated by Django 4.1.6 on 2023-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0003_remove_image_thumbnail_image_large_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='expiration_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
