# Generated by Django 4.1.6 on 2023-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0004_image_expiration_date_image_expiration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
