# Generated by Django 4.1.6 on 2023-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0005_image_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
