# Generated by Django 4.1.6 on 2023-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0006_image_expiration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='large_thumbnail_size',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='plan',
            name='small_thumbnail_size',
            field=models.IntegerField(default=200),
        ),
    ]
