# Generated by Django 4.1.6 on 2023-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0007_plan_large_thumbnail_size_plan_small_thumbnail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
