# Generated by Django 4.1.6 on 2023-02-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0008_alter_plan_name'),
        ('ImageUploader', '0009_auto_20230219_1528'),
    ]

    operations = [
    ]
