# Generated by Django 4.1.6 on 2023-02-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0010_merge_0008_alter_plan_name_0009_auto_20230219_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiry_time',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_public',
        ),
    ]
