# Generated by Django 4.1.6 on 2023-02-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0011_remove_image_expiry_time_remove_image_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_tier_users', to='ImageUploader.plan', to_field='name'),
        ),
    ]
